# Generated by Django 5.2.17 on 2026-09-15 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminologyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.URLField(max_length=500)),
                ("version", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=255)),
                ("source_label", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("display", models.CharField(max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("display", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.URLField(max_length=500)),
                ("version", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=255)),
                ("source_label", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=500)),
                ("presentation", models.CharField(max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "terminology_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medications",
                        to="catalogs.terminologyentry",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="terminologyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("system__regex", ".*\\S.*")),
                name="catalogs_terminologyentry_system_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminologyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__regex", ".*\\S.*")),
                name="catalogs_terminologyentry_version_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminologyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", ".*\\S.*")),
                name="catalogs_terminologyentry_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminologyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_label__regex", ".*\\S.*")),
                name="catalogs_terminologyentry_source_label_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminologyentry",
            constraint=models.UniqueConstraint(
                fields=("system", "version", "code"),
                name="catalogs_terminologyentry_source_version_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="terminologyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("display__regex", ".*\\S.*")),
                name="catalogs_terminologyentry_display_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("system__regex", ".*\\S.*")),
                name="catalogs_medicationentry_system_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__regex", ".*\\S.*")),
                name="catalogs_medicationentry_version_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", ".*\\S.*")),
                name="catalogs_medicationentry_code_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_label__regex", ".*\\S.*")),
                name="catalogs_medicationentry_source_label_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationentry",
            constraint=models.UniqueConstraint(
                fields=("system", "version", "code"),
                name="catalogs_medicationentry_source_version_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", ".*\\S.*")),
                name="catalogs_medicationentry_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("presentation__regex", ".*\\S.*")),
                name="catalogs_medicationentry_presentation_not_blank",
            ),
        ),
    ]
