# Generated by Django 5.2.17 on 2026-09-19

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_defer_clinical_record_generation"),
        ("professionals", "0007_specialty_unique_specialty_name_case_insensitive"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalClinicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_system", models.URLField(max_length=500)),
                ("resource_type", models.CharField(max_length=40)),
                ("external_identifier", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("observation", "Observation"),
                            ("medication-request", "Medication request"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_recorded_at", models.DateTimeField()),
                ("external_author", models.JSONField(editable=False)),
                ("content", models.JSONField(editable=False)),
                ("content_digest", models.CharField(editable=False, max_length=64)),
                (
                    "received_at",
                    models.DateTimeField(default=timezone.now, editable=False),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_clinical_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={"ordering": ("-source_recorded_at", "-id")},
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=timezone.now, editable=False),
                ),
                ("source_system", models.URLField(max_length=500)),
                ("bundle_identifier", models.CharField(max_length=500)),
                ("input_digest", models.CharField(editable=False, max_length=64)),
                ("request_key", models.UUIDField(editable=False)),
                ("raw_xml", models.BinaryField(editable=False)),
                ("summary", models.JSONField(editable=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_import_batches",
                        to="patients.patient",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_import_batches",
                        to="professionals.professional",
                    ),
                ),
            ],
            options={"ordering": ("-received_at", "-id")},
        ),
        migrations.CreateModel(
            name="ImportBatchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="interoperability.importbatch",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="interoperability.externalclinicalrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="importbatch",
            name="records",
            field=models.ManyToManyField(
                related_name="import_batches",
                through="interoperability.ImportBatchRecord",
                to="interoperability.externalclinicalrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("submitted_by", "patient", "request_key"),
                name="interop_batch_submitter_patient_request_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("patient", "source_system", "input_digest"),
                name="interop_batch_patient_source_digest_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_digest", ""), _negated=True),
                name="interop_batch_digest_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("bundle_identifier", ""), _negated=True),
                name="interop_batch_identifier_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalclinicalrecord",
            constraint=models.UniqueConstraint(
                fields=("source_system", "resource_type", "external_identifier"),
                name="interop_external_source_resource_identifier_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalclinicalrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("external_identifier", ""), _negated=True),
                name="interop_external_identifier_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalclinicalrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_digest", ""), _negated=True),
                name="interop_external_digest_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatchrecord",
            constraint=models.UniqueConstraint(
                fields=("batch", "record"), name="interop_batch_record_unique"
            ),
        ),
    ]
