# Generated by Django 5.2.17 on 2026-09-15 22:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0006_professional_license_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="specialty",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_specialty_name_case_insensitive",
            ),
        ),
    ]
