"""
Django settings for helixhealth project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", "production").strip().lower()


def load_local_environment(path):
    """Load a local environment file without overriding exported values."""
    if not path.is_file():
        return

    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        name, separator, value = line.partition("=")
        if not separator or not name.strip():
            raise ImproperlyConfigured(f"Invalid environment entry in {path}.")
        os.environ.setdefault(name.strip(), value.strip())


if ENVIRONMENT in {"development", "test"}:
    load_local_environment(BASE_DIR / ".env")


def env_bool(name, *, default=False):
    """Read a strict boolean environment variable."""
    value = os.environ.get(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(f"{name} must be a boolean value.")


def database_env(name, *, local_default):
    """Read a database setting, allowing defaults only for local use and tests."""
    value = os.environ.get(name)
    if value is not None:
        normalized = value.strip()
        if normalized:
            return normalized
    if ENVIRONMENT in {"development", "test"}:
        return local_default
    raise ImproperlyConfigured(
        f"{name} must be set outside the development and test environments."
    )


# manage.py opts into development; deployed ASGI/WSGI processes default to production.
DEBUG = env_bool("DJANGO_DEBUG", default=ENVIRONMENT == "development")

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if ENVIRONMENT != "development":
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set outside the development environment."
        )
    # An ephemeral key keeps local setup simple without committing a reusable secret.
    SECRET_KEY = secrets.token_urlsafe(50)

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_htmx",
    "patients.apps.PatientsConfig",
    "professionals.apps.ProfessionalsConfig",
    "clinical_records.apps.ClinicalRecordsConfig",
    "access_control.apps.AccessControlConfig",
    "audit.apps.AuditConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "access_control.middleware.MedicalProfessionalAdminRedirectMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "helixhealth.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.csrf",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "access_control.context_processors.actor_roles",
            ],
        },
    },
]

WSGI_APPLICATION = "helixhealth.wsgi.application"


# Authentication and request forgery protection

LOGIN_URL = "login"
LOGOUT_REDIRECT_URL = "login"

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = not DEBUG

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "HelixHealth API",
    "DESCRIPTION": "API contracts for the HelixHealth hospital information system.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# HU-03 application validation bounds. Deployments may override this complete
# mapping in an environment-specific settings module without changing schema.
CLINICAL_VITAL_SIGN_RANGES = {
    "systolic_blood_pressure": {
        "minimum": "70",
        "maximum": "250",
        "unit": "mmHg",
    },
    "diastolic_blood_pressure": {
        "minimum": "40",
        "maximum": "150",
        "unit": "mmHg",
    },
    "heart_rate": {
        "minimum": "30",
        "maximum": "220",
        "unit": "bpm",
    },
    "temperature": {
        "minimum": "30.0",
        "maximum": "45.0",
        "unit": "degrees Celsius",
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": database_env("DB_NAME", local_default="helixhealth_db"),
        "USER": database_env("DB_USER", local_default="helixhealth_app"),
        "PASSWORD": database_env("DB_PASSWORD", local_default="helixhealth_dev"),
        "HOST": database_env("DB_HOST", local_default="localhost"),
        "PORT": database_env("DB_PORT", local_default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
